### PR TITLE
Bug/61 - fix location updates not firing first time

### LINKED ISSUE #61: Fix initial location update not firing

### PR DESCRIPTION
**Pull request by samwoodall**
## Description
Make background location updates fire on first update and cache info about last location

## related issues
closes #61

### CODE REVIEW

File: location/src/main/kotlin/io/rover/campaigns/location/GoogleBackgroundLocationService.kt [hunk 1]
```diff
@@ -57,9 +65,27 @@ class GoogleBackgroundLocationService(
...
 
+    var currentLocation: Location?
+        get() {
+            return try {
+                val location = keyValueStorage[LOCATION_KEY]
+                location?.let {
+                    Location.decodeJson(JSONObject(it), dateFormatting)
+                }
+            } catch (e : JSONException) {
+                log.w("Failed to last known location JSON: $e")
```
Comment (orospakr) [inline location/src/main/kotlin/io/rover/campaigns/location/GoogleBackgroundLocationService.kt]: failed to *decode*? 😉

File: location/src/main/kotlin/io/rover/campaigns/location/GoogleBackgroundLocationService.kt [hunk 2]
```diff
@@ -126,7 +160,6 @@ class GoogleBackgroundLocationService(
                         .create()
                         .setInterval(LOCATION_UPDATE_INTERVAL)
                         .setFastestInterval(LOCATION_UPDATE_INTERVAL)
-                        .setSmallestDisplacement(minimumDisplacement)
```
Comment (orospakr) [inline location/src/main/kotlin/io/rover/campaigns/location/GoogleBackgroundLocationService.kt]: consider restoring this so google has opportunity to cut down on unnecessary updates from their side. initial update will still happen!

File: core/src/main/kotlin/io/rover/campaigns/core/data/domain/Location.kt [hunk 3]
```diff
@@ -42,7 +42,7 @@ data class Location(
             longitude = location.coordinate.longitude
         }
 
-        return loc1.distanceTo(loc2) < 100
+        return loc1.distanceTo(loc2) < 500f
```
Comment (orospakr) [inline core/src/main/kotlin/io/rover/campaigns/core/data/domain/Location.kt]: how about pulling this number out into a constant, and renaming this function to `isNotSignificantDisplacement` or something?

File: location/src/main/kotlin/io/rover/campaigns/location/GoogleBackgroundLocationService.kt [hunk 4]
```diff
@@ -52,7 +52,12 @@ class GoogleBackgroundLocationService(
     mainScheduler: Scheduler,
     private val trackLocation: Boolean = false,
     localStorage: LocalStorage,
-    private val dateFormatting: DateFormattingInterface
+    private val dateFormatting: DateFormattingInterface,
+    /**
+     * The minimum displacement in meters that will trigger a location update (and geofence/beacon
+     * rebinding).
+     */
+    private val minimumDisplacement: Float = 500f
```
Comment (orospakr) [inline location/src/main/kotlin/io/rover/campaigns/location/GoogleBackgroundLocationService.kt]: ditto, the other usage site of this constant.

File: core/src/main/kotlin/io/rover/campaigns/core/data/domain/Location.kt [hunk 5]
```diff
@@ -31,7 +31,7 @@ data class Location(
         companion object
     }
 
-    fun isWithinFiveHundredMeters(location: Location): Boolean {
+    fun isNotSignificantDisplacement(location: Location): Boolean {
```
Comment (orospakr) [inline core/src/main/kotlin/io/rover/campaigns/core/data/domain/Location.kt]: isSignifiantReplacement ? sry 😅
